title: SUSTech-Gardener
description: An autonomous mobile agricultural robot can collect agriculture-related information, as well as weeding and other work to serve the future agriculture.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
# theme: jekyll-theme-cayman